#docker-compose.yml
version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "db"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  backend_app:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "9229:9229"
    links:
      - db
    stdin_open: true
    tty: true